---
apiVersion: v1
kind: Template
metadata:
  name: cloudwatch-aggregator
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: cloudwatch-aggregator
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        metadata:
          annotations:
            email: Cloud-Platform-Infra@redhat.com
            owner: platform-infra
        env:
        - name: PUBLIC_PORT
          value: ${PUBLIC_PORT}
        - name: CLOUD_WATCH_ALLOWED_STREAMS
          value: ${CLOUD_WATCH_ALLOWED_STREAMS}
        - name: FLASK_ENV
          value: "${FLASK_ENV}"
        - name: LOG_TO_SPLUNK
          value: ${LOG_TO_SPLUNK}
        - name: LOG_TO_CLOUDWATCH
          value: ${LOG_TO_CLOUDWATCH}
        - name: SPLUNK_HOST
          value: ${SPLUNK_HOST}
        - name: SPLUNK_PORT
          value: ${SPLUNK_PORT}
        - name: SPLUNK_INDEX
          value: ${SPLUNK_INDEX}
        - name: SPLUNK_WAIT_ON_QUEUE
          value: ${SPLUNK_WAIT_ON_QUEUE}
        - name: SPLUNK_FORMAT_JSON
          value: ${SPLUNK_FORMAT_JSON}
        - name: SPLUNK_DEBUG
          value: ${SPLUNK_DEBUG}
        - name: SPLUNK_SOURCE_TYPE
          value: ${SPLUNK_SOURCE_TYPE}
        - name: REQUESTS_CA_BUNDLE
          value: ${REQUESTS_CA_BUNDLE}
        - name: SPLUNK_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: splunk
              optional: true
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: ${{PUBLIC_PORT}}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: ${{PUBLIC_PORT}}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumes:
        - name: trusted-certs-volume
          configMap:
            optional: true
            name: trusted-certs
        volumeMounts:
        - name: trusted-certs-volume
          mountPath: /etc/ssl/certs/${TRUSTED_CERT_FILENAME}
          subPath: ${TRUSTED_CERT_FILENAME}
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cloudwatch-aggregator
    name: cloudwatch-aggregator
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8000
    selector:
      pod: cloudwatch-aggregator-service
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: ServiceAccount
  metadata:
   name: cloudwatch-aggregator

parameters:
- name: CLOUD_WATCH_ALLOWED_STREAMS
  value: 3scale,3scale-dev,3scale-staging
- name: MIN_REPLICAS
  value: "1"
- name: IMAGE_TAG
  required: true
- name: IMAGE
  value: quay.io/cloudservices/cloudwatch-aggregator
  required: true
- name: MEMORY_LIMIT
  value: 1Gi
  required: true
- name: MEMORY_REQUEST
  value: 750Mi
  required: true
- name: CPU_LIMIT
  value: 500m
  required: true
- name: CPU_REQUEST
  value: 100m
  required: true
- description: Value for FLASK_ENV
  name: FLASK_ENV
  value: production
  required: true
- description: Port to listen on
  name: PUBLIC_PORT
  value: "8000"
  required: true
- description: Environment
  name: ENV_NAME
  value: cloudwatch-aggregator
  required: true
- description: Flag to enable logging to Splunk
  name: LOG_TO_SPLUNK
  value: "false"
- description: Flag to enable logging to CloudWatch
  name: LOG_TO_CLOUDWATCH
  value: "false"
- description: Splunk instance host
  name: SPLUNK_HOST
- description: Splunk host port
  name: SPLUNK_PORT
- description: Splunk log index
  name: SPLUNK_INDEX
  value: "main"
- description: Flag to have Splunk wait when the queue is full (if false it will drop logs)
  name: SPLUNK_WAIT_ON_QUEUE
  value: "true"
- description: Flag to format Splunk logs as JSON
  name: SPLUNK_FORMAT_JSON
  value: "true"
- description: Flag to enable Splunk debug logs
  name: SPLUNK_DEBUG
  value: "false"
- description: Source type for logs to Splunk
  name: SPLUNK_SOURCE_TYPE
  value: "json"
- description: Sub path / filename to mount the trusted cert configMap
  name: TRUSTED_CERT_FILENAME
  value: "placeholder.pem"
- description: Explicitly set the CA path for Python to use
  name: REQUESTS_CA_BUNDLE
