apiVersion: v1
kind: Template
metadata:
  name: cloudwatch-aggregator
objects:
- apiVersion: cloud.redhat.com/v1alpha1 
  kind: ClowdApp
  metadata:
    name: cloudwatch-aggregator
    labels:
      app: cloudwatch-aggregator
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - gateway
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        serviceAccountName: cloudwatch-aggregator
        env:
        - name: PUBLIC_PORT
          value: ${PUBLIC_PORT}
        - name: CLOUD_WATCH_ALLOWED_STREAMS
          value: ${CLOUD_WATCH_ALLOWED_STREAMS}
        - name: FLASK_ENV
          value: "${FLASK_ENV}"
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: cwa
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cloudwatch-aggregator
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: cwa
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}

parameters:
- name: CLOUD_WATCH_ALLOWED_STREAMS
  value: 3scale,3scale-dev,3scale-staging
- name: MIN_REPLICAS
  value: "1"
- name: IMAGE_TAG
  required: true
- name: IMAGE
  value: quay.io/cloudservices/cloudwatch-aggregator
  required: true
- name: MEMORY_LIMIT
  value: 1Gi
  required: true
- name: MEMORY_REQUEST
  value: 750Mi
  required: true
- name: CPU_LIMIT
  value: 500m
  required: true
- name: CPU_REQUEST
  value: 100m
  required: true
- description: Value for FLASK_ENV
  name: FLASK_ENV
  value: production
  required: true
- description: Port to listen on
  name: PUBLIC_PORT
  value: 8000 
  required: true
- description: Environment
  name: ENV_NAME
  value: cloudwatch-aggregator
  required: true

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cloudwatch-aggregator
    name: cloudwatch-aggregator
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8000 
    selector:
      app: cloudwatch-aggregator
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cloudwatch-aggregator
